=== VKCOM/vk-api-schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "API",
  "description": "VK API declaration",
  "type": "object",
  "definitions": {
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "int32",
        "int64"
      ]
    },
    "enumNames": {
      "type": "array",
      "description": "Enum values text representations",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "jsonReference": {
      "type": "object",
      "required": [
        "$ref"
      ],
      "additionalProperties": false,
      "properties": {
        "$ref": {
          "type": "string"
        }
      }
    },
    "parameterArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "parameterTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "responseTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string",
        "object"
      ]
    },
    "responsePropertyTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "itemTypes": {
      "type": "string",
      "enum": [
        "object",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "parameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$",
          "description": "Parameter name"
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "type": {
          "$ref": "#/definitions/parameterTypes",
          "description": "Parameter type"
        },
        "items": {
          "type": "object",
          "properties": {
            "$ref": {
              "type": "string",
              "format": "uri-reference"
            },
            "type": {
              "$ref": "#/definitions/itemTypes"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "maximum": {
              "type": "number"
            },
            "minimum": {
              "type": "number"
            },
            "minLength": {
              "type": "integer",
              "minimum": 0,
              "default": 0
            },
            "maxLength": {
              "type": "integer",
              "minimum": 0
            },
            "enum": {
              "type": "array",
              "description": "Allowed enumerable values",
              "$ref": "#/definitions/enum"
            },
            "enumNames": {
              "$ref": "#/definitions/enumNames"
            }
          },
          "oneOf": [
            {
              "required": [
                "type"
              ]
            },
            {
              "required": [
                "$ref"
              ]
            }
          ],
          "additionalProperties": false
        },
        "maxItems": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "maximum": {
          "type": "number"
        },
        "minimum": {
          "type": "number"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "enum": {
          "type": "array",
          "$ref": "#/definitions/enum"
        },
        "enumNames": {
          "$ref": "#/definitions/enumNames"
        },
        "default": {
          "description": "Default property value"
        },
        "required": {
          "type": "boolean",
          "default": false
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        },
        "minLength": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "description": {
          "type": "string",
          "description": "Parameter description"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "responseProperty": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "type"
          ]
        },
        {
          "required": [
            "$ref"
          ]
        }
      ],
      "properties": {
        "type": {
          "$ref": "#/definitions/responseTypes"
        },
        "description": {
          "type": "string"
        }
      }
    },
    "response": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/response"
          }
        },
        "items": {
          "oneOf": [
            {
              "type": "array"
            },
            {
              "type": "object",
              "properties": {
                "$ref": {
                  "type": "string"
                }
              }
            }
          ]
        },
        "required": {
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "oneOf": {
          "type": "array"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "properties": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9_]+$": {
              "$ref": "#/definitions/responseProperty"
            }
          },
          "additionalProperties": false
        },
        "additionalProperties": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "description": "Error code",
          "minimum": 0
        },
        "description": {
          "type": "string",
          "description": "Error description"
        },
        "subcodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/error_subcode"
          },
          "description": "Array of error subcodes"
        },
        "global": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "code",
        "description"
      ],
      "additionalProperties": false
    },
    "error_subcode": {
      "type": "object",
      "properties": {
        "subcode": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        }
      },
      "additionalProperties": false
    },
    "methodErrors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "$ref": {
            "type": "string",
            "format": "uri-reference"
          }
        },
        "additionalProperties": false
      },
      "description": "Possible custom errors"
    },
    "method": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9.]+$",
          "description": "Method name"
        },
        "description": {
          "type": "string",
          "description": "Method description"
        },
        "timeout": {
          "type": "integer",
          "minimum": 1,
          "maximum": 30
        },
        "access_token_type": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "open",
              "user",
              "group",
              "service"
            ],
            "description": "Access token type"
          },
          "description": "Input parameters for method"
        },
        "parameters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/parameter"
          },
          "description": "Input parameters for method"
        },
        "responses": {
          "type": "object",
          "patternProperties": {
            "^([a-zA-Z0-9_]+)?[rR]esponse$": {
              "$ref": "#/definitions/response"
            }
          },
          "additionalProperties": true,
          "description": "References to response objects"
        },
        "emptyResponse": {
          "type": "boolean",
          "default": false
        },
        "errors": {
          "$ref": "#/definitions/methodErrors"
        }
      },
      "required": [
        "name",
        "access_token_type",
        "responses"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "errors": {
      "type": "object",
      "patternProperties": {
        "^[a-z][a-z0-9_]+$": {
          "$ref": "#/definitions/error"
        }
      },
      "additionalProperties": false,
      "uniqueProperties": true
    },
    "methods": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/method"
      }
    },
    "definitions": {
      "patternProperties": {
        "^([a-zA-Z0-9_]+)?[rR]esponse$": {
          "$ref": "#/definitions/response"
        }
      },
      "uniqueProperties": true
    },
    "$schema": {
      "type": "string",
      "format": "uri-reference"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "termsOfService": {
      "type": "string",
      "format": "url"
    },
    "version": {
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== VKCOM/vk-api-schema/asr/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "asr_checkStatus_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../asr/objects.json#/definitions/asr_task",
          "required": true,
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "asr_process_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "task_id": {
              "type": "string",
              "required": true,
              "description": "ID of created task in UUID format."
            }
          },
          "required": true,
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/prettyCards/methods.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "version": "5.131",
  "title": "VK API JSON Schema",
  "description": "Contains JSON Schema documents explaining the VK.COM API objects and methods",
  "termsOfService": "https://dev.vk.com/rules",
  "methods": [
    {
      "name": "prettyCards.create",
      "access_token_type": [
        "user"
      ],
      "parameters": [
        {
          "name": "owner_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "photo",
          "type": "string",
          "required": true
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        },
        {
          "name": "link",
          "type": "string",
          "required": true,
          "maxLength": 2000
        },
        {
          "name": "price",
          "type": "string",
          "maxLength": 20
        },
        {
          "name": "price_old",
          "type": "string",
          "maxLength": 20
        },
        {
          "name": "button",
          "type": "string",
          "maxLength": 255
        }
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_create_response"
        }
      },
      "errors": [
        {
          "$ref": "../errors.json#/errors/api_error_pretty_cards_too_many_cards"
        }
      ]
    },
    {
      "name": "prettyCards.delete",
      "access_token_type": [
        "user"
      ],
      "parameters": [
        {
          "name": "owner_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "card_id",
          "type": "integer",
          "required": true
        }
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_delete_response"
        }
      },
      "errors": [
        {
          "$ref": "../errors.json#/errors/api_error_pretty_cards_card_not_found"
        },
        {
          "$ref": "../errors.json#/errors/api_error_pretty_cards_card_is_connected_to_post"
        }
      ]
    },
    {
      "name": "prettyCards.edit",
      "access_token_type": [
        "user"
      ],
      "parameters": [
        {
          "name": "owner_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "card_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "photo",
          "type": "string"
        },
        {
          "name": "title",
          "type": "string"
        },
        {
          "name": "link",
          "type": "string",
          "maxLength": 2000
        },
        {
          "name": "price",
          "type": "string",
          "maxLength": 20
        },
        {
          "name": "price_old",
          "type": "string",
          "maxLength": 20
        },
        {
          "name": "button",
          "type": "string",
          "maxLength": 255
        }
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_edit_response"
        }
      },
      "errors": [
        {
          "$ref": "../errors.json#/errors/api_error_pretty_cards_card_not_found"
        }
      ]
    },
    {
      "name": "prettyCards.get",
      "access_token_type": [
        "user"
      ],
      "parameters": [
        {
          "name": "owner_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "offset",
          "type": "integer",
          "default": 0,
          "minimum": 0
        },
        {
          "name": "count",
          "type": "integer",
          "default": 10,
          "minimum": 0,
          "maximum": 100
        }
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_get_response"
        }
      }
    },
    {
      "name": "prettyCards.getById",
      "access_token_type": [
        "user"
      ],
      "parameters": [
        {
          "name": "owner_id",
          "type": "integer",
          "required": true
        },
        {
          "name": "card_ids",
          "type": "array",
          "required": true,
          "items": {
            "type": "integer"
          },
          "maxItems": 10
        }
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_getById_response"
        }
      }
    },
    {
      "name": "prettyCards.getUploadURL",
      "access_token_type": [
        "user"
      ],
      "responses": {
        "response": {
          "$ref": "../prettyCards/responses.json#/definitions/prettyCards_getUploadURL_response"
        }
      }
    }
  ]
}

=== VKCOM/vk-api-schema/link/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "link_target_object": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Object type"
        },
        "owner_id": {
          "type": "integer",
          "description": "Owner ID",
          "entity": "owner",
          "format": "int64"
        },
        "item_id": {
          "type": "integer",
          "description": "Item ID"
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/calls/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "calls_start_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "call_id": {
              "type": "string",
              "description": "Call id"
            },
            "join_link": {
              "type": "string",
              "description": "Join link",
              "required": true
            },
            "ok_join_link": {
              "type": "string",
              "description": "OK join link",
              "required": true
            },
            "broadcast_video_id": {
              "type": "string",
              "description": "video id for link"
            },
            "broadcast_ov_id": {
              "type": "string",
              "description": "video id for streaming"
            },
            "short_credentials": {
              "$ref": "../calls/objects.json#/definitions/calls_short_credentials"
            }
          },
          "required": true
        }
      }
    }
  }
}

=== VKCOM/vk-api-schema/polls/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "polls_answer": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "description": "Answer ID",
          "minimum": 0,
          "required": true
        },
        "rate": {
          "type": "number",
          "description": "Answer rate in percents",
          "minimum": 0,
          "required": true
        },
        "text": {
          "type": "string",
          "description": "Answer text",
          "required": true
        },
        "votes": {
          "type": "integer",
          "description": "Votes number",
          "minimum": 0,
          "required": true
        }
      }
    },
    "polls_background": {
      "type": "object",
      "properties": {
        "angle": {
          "description": "Gradient angle with 0 on positive X axis",
          "type": "integer"
        },
        "color": {
          "type": "string",
          "description": "Hex color code without #"
        },
        "height": {
          "description": "Original height of pattern tile",
          "type": "integer",
          "minimum": 0
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "images": {
          "description": "Pattern tiles",
          "type": "array",
          "items": {
            "$ref": "../base/objects.json#/definitions/base_image"
          }
        },
        "points": {
          "description": "Gradient points",
          "type": "array",
          "items": {
            "$ref": "../base/objects.json#/definitions/base_gradient_point"
          }
        },
        "type": {
          "type": "string",
          "enum": [
            "gradient",
            "tile"
          ]
        },
        "width": {
          "description": "Original with of pattern tile",
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "polls_fields_voters": {
      "type": "object",
      "properties": {
        "answer_id": {
          "type": "integer",
          "format": "int64",
          "description": "Answer ID"
        },
        "users": {
          "$ref": "../polls/objects.json#/definitions/polls_voters_fields_users"
        },
        "answer_offset": {
          "type": "string",
          "description": "Answer offset"
        }
      }
    },
    "polls_friend": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "entity": "owner",
          "minimum": 0,
          "format": "int64",
          "required": true
        }
      }
    },
    "polls_poll": {
      "type": "object",
      "properties": {
        "anonymous": {
          "$ref": "../polls/objects.json#/definitions/polls_poll_anonymous"
        },
        "friends": {
          "type": "array",
          "items": {
            "$ref": "../polls/objects.json#/definitions/polls_friend"
          }
        },
        "multiple": {
          "description": "Information whether the poll with multiple choices",
          "type": "boolean",
          "required": true
        },
        "answer_id": {
          "type": "integer",
          "format": "int64",
          "description": "Current user's answer ID",
          "minimum": 0
        },
        "end_date": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "answer_ids": {
          "type": "array",
          "description": "Current user's answer IDs",
          "items": {
            "type": "integer",
            "format": "int64",
            "minimum": 0
          }
        },
        "closed": {
          "type": "boolean",
          "required": true
        },
        "is_board": {
          "type": "boolean",
          "required": true
        },
        "can_edit": {
          "type": "boolean",
          "required": true
        },
        "can_vote": {
          "type": "boolean",
          "required": true
        },
        "can_report": {
          "type": "boolean",
          "required": true
        },
        "can_share": {
          "type": "boolean",
          "required": true
        },
        "embed_hash": {
          "type": "string"
        },
        "photo": {
          "$ref": "../polls/objects.json#/definitions/polls_background"
        },
        "answers": {
          "type": "array",
          "items": {
            "$ref": "../polls/objects.json#/definitions/polls_answer"
          },
          "required": true
        },
        "created": {
          "type": "integer",
          "description": "Date when poll has been created in Unixtime",
          "minimum": 0,
          "required": true
        },
        "id": {
          "type": "integer",
          "description": "Poll ID",
          "minimum": 1,
          "required": true
        },
        "owner_id": {
          "type": "integer",
          "entity": "owner",
          "description": "Poll owner's ID",
          "format": "int64",
          "required": true
        },
        "author_id": {
          "type": "integer",
          "description": "Poll author's ID"
        },
        "question": {
          "type": "string",
          "description": "Poll question",
          "required": true
        },
        "background": {
          "$ref": "../polls/objects.json#/definitions/polls_background"
        },
        "votes": {
          "type": "integer",
          "description": "Votes number",
          "minimum": 0,
          "required": true
        },
        "disable_unvote": {
          "type": "boolean",
          "required": true
        }
      }
    },
    "polls_poll_anonymous": {
      "type": "boolean",
      "description": "Information whether the field is anonymous"
    },
    "polls_poll_extended": {
      "type": "object",
      "allOf": [
        {
          "$ref": "../polls/objects.json#/definitions/polls_poll"
        },
        {
          "properties": {
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "../users/objects.json#/definitions/users_user_full"
              }
            }
          }
        }
      ]
    },
    "polls_voters": {
      "type": "object",
      "properties": {
        "answer_id": {
          "type": "integer",
          "format": "int64",
          "description": "Answer ID"
        },
        "users": {
          "$ref": "../polls/objects.json#/definitions/polls_voters_users"
        },
        "answer_offset": {
          "type": "string",
          "description": "Answer offset"
        }
      }
    },
    "polls_voters_fields_users": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "minimum": 0,
          "description": "Votes number"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "../users/objects.json#/definitions/users_user_full"
          }
        }
      }
    },
    "polls_voters_users": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "minimum": 0,
          "description": "Votes number"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "integer",
            "entity": "profiles",
            "format": "int64",
            "description": "User ID"
          }
        }
      }
    }
  }
}
