=== VKCOM/vk-api-schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "API",
  "description": "VK API declaration",
  "type": "object",
  "definitions": {
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "int32",
        "int64"
      ]
    },
    "enumNames": {
      "type": "array",
      "description": "Enum values text representations",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "jsonReference": {
      "type": "object",
      "required": [
        "$ref"
      ],
      "additionalProperties": false,
      "properties": {
        "$ref": {
          "type": "string"
        }
      }
    },
    "parameterArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "parameterTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "responseTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string",
        "object"
      ]
    },
    "responsePropertyTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "itemTypes": {
      "type": "string",
      "enum": [
        "object",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "parameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$",
          "description": "Parameter name"
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "type": {
          "$ref": "#/definitions/parameterTypes",
          "description": "Parameter type"
        },
        "items": {
          "type": "object",
          "properties": {
            "$ref": {
              "type": "string",
              "format": "uri-reference"
            },
            "type": {
              "$ref": "#/definitions/itemTypes"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "maximum": {
              "type": "number"
            },
            "minimum": {
              "type": "number"
            },
            "minLength": {
              "type": "integer",
              "minimum": 0,
              "default": 0
            },
            "maxLength": {
              "type": "integer",
              "minimum": 0
            },
            "enum": {
              "type": "array",
              "description": "Allowed enumerable values",
              "$ref": "#/definitions/enum"
            },
            "enumNames": {
              "$ref": "#/definitions/enumNames"
            }
          },
          "oneOf": [
            {
              "required": [
                "type"
              ]
            },
            {
              "required": [
                "$ref"
              ]
            }
          ],
          "additionalProperties": false
        },
        "maxItems": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "maximum": {
          "type": "number"
        },
        "minimum": {
          "type": "number"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "enum": {
          "type": "array",
          "$ref": "#/definitions/enum"
        },
        "enumNames": {
          "$ref": "#/definitions/enumNames"
        },
        "default": {
          "description": "Default property value"
        },
        "required": {
          "type": "boolean",
          "default": false
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        },
        "minLength": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "description": {
          "type": "string",
          "description": "Parameter description"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "responseProperty": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "type"
          ]
        },
        {
          "required": [
            "$ref"
          ]
        }
      ],
      "properties": {
        "type": {
          "$ref": "#/definitions/responseTypes"
        },
        "description": {
          "type": "string"
        }
      }
    },
    "response": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/response"
          }
        },
        "items": {
          "oneOf": [
            {
              "type": "array"
            },
            {
              "type": "object",
              "properties": {
                "$ref": {
                  "type": "string"
                }
              }
            }
          ]
        },
        "required": {
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "oneOf": {
          "type": "array"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "properties": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9_]+$": {
              "$ref": "#/definitions/responseProperty"
            }
          },
          "additionalProperties": false
        },
        "additionalProperties": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "description": "Error code",
          "minimum": 0
        },
        "description": {
          "type": "string",
          "description": "Error description"
        },
        "subcodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/error_subcode"
          },
          "description": "Array of error subcodes"
        },
        "global": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "code",
        "description"
      ],
      "additionalProperties": false
    },
    "error_subcode": {
      "type": "object",
      "properties": {
        "subcode": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        }
      },
      "additionalProperties": false
    },
    "methodErrors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "$ref": {
            "type": "string",
            "format": "uri-reference"
          }
        },
        "additionalProperties": false
      },
      "description": "Possible custom errors"
    },
    "method": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9.]+$",
          "description": "Method name"
        },
        "description": {
          "type": "string",
          "description": "Method description"
        },
        "timeout": {
          "type": "integer",
          "minimum": 1,
          "maximum": 30
        },
        "access_token_type": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "open",
              "user",
              "group",
              "service"
            ],
            "description": "Access token type"
          },
          "description": "Input parameters for method"
        },
        "parameters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/parameter"
          },
          "description": "Input parameters for method"
        },
        "responses": {
          "type": "object",
          "patternProperties": {
            "^([a-zA-Z0-9_]+)?[rR]esponse$": {
              "$ref": "#/definitions/response"
            }
          },
          "additionalProperties": true,
          "description": "References to response objects"
        },
        "emptyResponse": {
          "type": "boolean",
          "default": false
        },
        "errors": {
          "$ref": "#/definitions/methodErrors"
        }
      },
      "required": [
        "name",
        "access_token_type",
        "responses"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "errors": {
      "type": "object",
      "patternProperties": {
        "^[a-z][a-z0-9_]+$": {
          "$ref": "#/definitions/error"
        }
      },
      "additionalProperties": false,
      "uniqueProperties": true
    },
    "methods": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/method"
      }
    },
    "definitions": {
      "patternProperties": {
        "^([a-zA-Z0-9_]+)?[rR]esponse$": {
          "$ref": "#/definitions/response"
        }
      },
      "uniqueProperties": true
    },
    "$schema": {
      "type": "string",
      "format": "uri-reference"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "termsOfService": {
      "type": "string",
      "format": "url"
    },
    "version": {
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== VKCOM/vk-api-schema/bugtracker/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "bugtracker_addCompanyGroupsMembers_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "errors": {
              "type": "array",
              "items": {
                "$ref": "../bugtracker/objects.json#/definitions/bugtracker_add_company_groups_members_error"
              },
              "required": true
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_addCompanyMembers_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "errors": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "required": true
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_createComment_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "comment": {
              "$ref": "../bugtracker/objects.json#/definitions/bugtracker_comment",
              "required": true
            },
            "comment_flood": {
              "type": "boolean"
            },
            "subscribe_state": {
              "$ref": "../bugtracker/objects.json#/definitions/bugtracker_bugreport_subscribe_state"
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_getBugreportById_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "bugreport": {
              "$ref": "../bugtracker/objects.json#/definitions/bugtracker_bugreport"
            },
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "../users/objects.json#/definitions/users_user_full"
              }
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_getCompanyGroupMembers_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "user_ids": {
              "type": "array",
              "items": {
                "type": "integer",
                "minimum": 0,
                "entity": "owner",
                "format": "int64"
              },
              "required": true
            },
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "../users/objects.json#/definitions/users_user_full"
              }
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_getCompanyMembers_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "company_members": {
              "type": "array",
              "items": {
                "$ref": "../bugtracker/objects.json#/definitions/bugtracker_company_member"
              },
              "required": true
            },
            "count": {
              "type": "integer",
              "required": true
            },
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "../users/objects.json#/definitions/users_user_full"
              }
            }
          },
          "required": true
        }
      }
    },
    "bugtracker_getDownloadVersionUrl_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "required": true
            },
            "app_title": {
              "type": "string"
            },
            "bundle_name": {
              "type": "string"
            },
            "build_id": {
              "type": "integer"
            },
            "build_name": {
              "type": "string"
            },
            "build_title": {
              "type": "string"
            }
          },
          "required": true
        }
      }
    }
  }
}

=== VKCOM/vk-api-schema/widgets/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "widgets_getComments_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer",
              "description": "Total number",
              "required": true
            },
            "posts": {
              "type": "array",
              "items": {
                "$ref": "../widgets/objects.json#/definitions/widgets_widget_comment"
              },
              "required": true
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "widgets_getPages_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer",
              "description": "Total number",
              "required": true
            },
            "pages": {
              "type": "array",
              "items": {
                "$ref": "../widgets/objects.json#/definitions/widgets_widget_page"
              },
              "required": true
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/notifications/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "notifications_get_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer",
              "description": "Total number",
              "required": true
            },
            "items": {
              "type": "array",
              "items": {
                "$ref": "../notifications/objects.json#/definitions/notifications_notification_item"
              },
              "required": true
            },
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "../users/objects.json#/definitions/users_user"
              }
            },
            "groups": {
              "type": "array",
              "items": {
                "$ref": "../groups/objects.json#/definitions/groups_group"
              }
            },
            "last_viewed": {
              "type": "integer",
              "description": "Time when user has been checked notifications last time"
            },
            "photos": {
              "type": "array",
              "items": {
                "$ref": "../photos/objects.json#/definitions/photos_photo"
              }
            },
            "videos": {
              "type": "array",
              "items": {
                "$ref": "../video/objects.json#/definitions/video_video"
              }
            },
            "apps": {
              "type": "array",
              "items": {
                "$ref": "../apps/objects.json#/definitions/apps_app"
              }
            },
            "next_from": {
              "type": "string"
            },
            "ttl": {
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "notifications_sendMessage_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../notifications/objects.json#/definitions/notifications_send_message_item"
          },
          "required": true
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/prettyCards/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "prettyCards_button_one_of": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "$ref": "../base/objects.json#/definitions/base_link_button"
        },
        {
          "type": "string"
        }
      ]
    },
    "prettyCards_prettyCard": {
      "type": "object",
      "properties": {
        "inner_type": {
          "type": "string",
          "required": true,
          "enum": [
            "prettyCards_prettyCard"
          ],
          "default": "prettyCards_prettyCard"
        },
        "button": {
          "description": "Button key",
          "$ref": "../prettyCards/objects.json#/definitions/prettyCards_button_one_of"
        },
        "button_text": {
          "type": "string",
          "description": "Button text in current language"
        },
        "card_id": {
          "type": "string",
          "description": "Card ID (long int returned as string)",
          "required": true
        },
        "images": {
          "type": "array",
          "items": {
            "$ref": "../base/objects.json#/definitions/base_image"
          }
        },
        "link_url": {
          "type": "string",
          "description": "Link URL",
          "required": true
        },
        "photo": {
          "type": "string",
          "description": "Photo ID (format \"<owner_id>_<media_id>\")",
          "required": true
        },
        "price": {
          "type": "string",
          "description": "Price if set (decimal number returned as string)"
        },
        "price_old": {
          "type": "string",
          "description": "Old price if set (decimal number returned as string)"
        },
        "title": {
          "type": "string",
          "description": "Title",
          "required": true
        }
      }
    },
    "prettyCards_prettyCardOrError": {
      "type": "object",
      "discriminator": {
        "propertyName": "inner_type",
        "mapping": {
          "prettyCards_prettyCard": "../prettyCards/objects.json#/definitions/prettyCards_prettyCard",
          "base_error": "../base/objects.json#/definitions/base_error"
        }
      },
      "oneOf": [
        {
          "$ref": "../prettyCards/objects.json#/definitions/prettyCards_prettyCard"
        },
        {
          "$ref": "../base/objects.json#/definitions/base_error"
        }
      ]
    }
  }
}

=== VKCOM/vk-api-schema/oauth/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "oauth_error": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "description": "Error type",
          "required": true
        },
        "error_description": {
          "type": "string",
          "description": "Error description",
          "required": true
        },
        "redirect_uri": {
          "type": "string",
          "description": "URI for validation"
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/leadForms/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "leadForms_create_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "form_id": {
              "type": "integer",
              "required": true
            },
            "url": {
              "type": "string",
              "format": "uri",
              "required": true
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "leadForms_delete_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "form_id": {
              "type": "integer",
              "required": true
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "leadForms_getLeads_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "leads": {
              "type": "array",
              "items": {
                "$ref": "../leadForms/objects.json#/definitions/leadForms_lead"
              },
              "required": true
            },
            "next_page_token": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "leadForms_get_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../leadForms/objects.json#/definitions/leadForms_form",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "leadForms_list_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../leadForms/objects.json#/definitions/leadForms_form"
          },
          "required": true
        }
      },
      "additionalProperties": false
    },
    "leadForms_uploadUrl_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "string",
          "format": "uri",
          "required": true
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/bugtracker/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "bugtracker_add_company_groups_members_error": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "integer",
          "minimum": 0,
          "required": true,
          "entity": "groups",
          "format": "int64"
        },
        "user_id": {
          "type": "integer",
          "minimum": 0,
          "entity": "owner",
          "format": "int64",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "bugtracker_attachment": {
      "type": "object",
      "properties": {
        "doc": {
          "$ref": "../docs/objects.json#/definitions/docs_doc"
        },
        "photo": {
          "$ref": "../photos/objects.json#/definitions/photos_photo"
        },
        "type": {
          "type": "string",
          "enum": [
            "photo",
            "doc"
          ],
          "required": true
        }
      },
      "additionalProperties": false
    },
    "bugtracker_bugreport_subscribe_state": {
      "type": "object",
      "properties": {
        "can_set_subscribe": {
          "type": "boolean",
          "required": true
        },
        "is_subscribed": {
          "type": "boolean"
        },
        "set_subscribe_hash": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "bugtracker_comment": {
      "type": "object",
      "properties": {
        "bugreport_id": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "comment_id": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "created": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "text": {
          "type": "string",
          "required": true
        },
        "meta_text": {
          "type": "string"
        },
        "from_id": {
          "type": "integer"
        },
        "author_name": {
          "type": "string"
        },
        "author_photo": {
          "type": "string"
        },
        "edit_hash": {
          "type": "string"
        },
        "remove_hash": {
          "type": "string"
        },
        "is_hidden": {
          "type": "boolean"
        },
        "attachments": {
          "type": "array",
          "items": {
            "$ref": "../bugtracker/objects.json#/definitions/bugtracker_attachment"
          }
        },
        "is_unread": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "bugtracker_company_member": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "integer",
          "minimum": 0,
          "entity": "owner",
          "format": "int64",
          "required": true
        },
        "company_id": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "role": {
          "type": "integer",
          "required": true
        },
        "role_name": {
          "type": "string",
          "required": true
        },
        "ts": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "groups_count": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "products_count": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "reporter_url": {
          "type": "string",
          "required": true
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "products": {
          "type": "array",
          "items": {
            "$ref": "../bugtracker/objects.json#/definitions/bugtracker_company_member_product"
          }
        }
      },
      "additionalProperties": false
    },
    "bugtracker_company_member_product": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "title": {
          "type": "string"
        },
        "photo_url": {
          "type": "string"
        },
        "access": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "status": {
          "type": "integer",
          "minimum": 0,
          "required": true
        },
        "licence_status_text": {
          "type": "string",
          "minimum": 0
        }
      },
      "additionalProperties": false
    }
  }
}
