=== VKCOM/vk-api-schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "API",
  "description": "VK API declaration",
  "type": "object",
  "definitions": {
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "int32",
        "int64"
      ]
    },
    "enumNames": {
      "type": "array",
      "description": "Enum values text representations",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "jsonReference": {
      "type": "object",
      "required": [
        "$ref"
      ],
      "additionalProperties": false,
      "properties": {
        "$ref": {
          "type": "string"
        }
      }
    },
    "parameterArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "parameterTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "responseTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string",
        "object"
      ]
    },
    "responsePropertyTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "itemTypes": {
      "type": "string",
      "enum": [
        "object",
        "boolean",
        "integer",
        "number",
        "string"
      ]
    },
    "parameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$",
          "description": "Parameter name"
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "type": {
          "$ref": "#/definitions/parameterTypes",
          "description": "Parameter type"
        },
        "items": {
          "type": "object",
          "properties": {
            "$ref": {
              "type": "string",
              "format": "uri-reference"
            },
            "type": {
              "$ref": "#/definitions/itemTypes"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "maximum": {
              "type": "number"
            },
            "minimum": {
              "type": "number"
            },
            "minLength": {
              "type": "integer",
              "minimum": 0,
              "default": 0
            },
            "maxLength": {
              "type": "integer",
              "minimum": 0
            },
            "enum": {
              "type": "array",
              "description": "Allowed enumerable values",
              "$ref": "#/definitions/enum"
            },
            "enumNames": {
              "$ref": "#/definitions/enumNames"
            }
          },
          "oneOf": [
            {
              "required": [
                "type"
              ]
            },
            {
              "required": [
                "$ref"
              ]
            }
          ],
          "additionalProperties": false
        },
        "maxItems": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "maximum": {
          "type": "number"
        },
        "minimum": {
          "type": "number"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "enum": {
          "type": "array",
          "$ref": "#/definitions/enum"
        },
        "enumNames": {
          "$ref": "#/definitions/enumNames"
        },
        "default": {
          "description": "Default property value"
        },
        "required": {
          "type": "boolean",
          "default": false
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        },
        "minLength": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "description": {
          "type": "string",
          "description": "Parameter description"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "responseProperty": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "type"
          ]
        },
        {
          "required": [
            "$ref"
          ]
        }
      ],
      "properties": {
        "type": {
          "$ref": "#/definitions/responseTypes"
        },
        "description": {
          "type": "string"
        }
      }
    },
    "response": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/response"
          }
        },
        "items": {
          "oneOf": [
            {
              "type": "array"
            },
            {
              "type": "object",
              "properties": {
                "$ref": {
                  "type": "string"
                }
              }
            }
          ]
        },
        "required": {
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "oneOf": {
          "type": "array"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "properties": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9_]+$": {
              "$ref": "#/definitions/responseProperty"
            }
          },
          "additionalProperties": false
        },
        "additionalProperties": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "description": "Error code",
          "minimum": 0
        },
        "description": {
          "type": "string",
          "description": "Error description"
        },
        "subcodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/error_subcode"
          },
          "description": "Array of error subcodes"
        },
        "global": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "code",
        "description"
      ],
      "additionalProperties": false
    },
    "error_subcode": {
      "type": "object",
      "properties": {
        "subcode": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        }
      },
      "additionalProperties": false
    },
    "methodErrors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "$ref": {
            "type": "string",
            "format": "uri-reference"
          }
        },
        "additionalProperties": false
      },
      "description": "Possible custom errors"
    },
    "method": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z][a-zA-Z0-9.]+$",
          "description": "Method name"
        },
        "description": {
          "type": "string",
          "description": "Method description"
        },
        "timeout": {
          "type": "integer",
          "minimum": 1,
          "maximum": 30
        },
        "access_token_type": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "open",
              "user",
              "group",
              "service"
            ],
            "description": "Access token type"
          },
          "description": "Input parameters for method"
        },
        "parameters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/parameter"
          },
          "description": "Input parameters for method"
        },
        "responses": {
          "type": "object",
          "patternProperties": {
            "^([a-zA-Z0-9_]+)?[rR]esponse$": {
              "$ref": "#/definitions/response"
            }
          },
          "additionalProperties": true,
          "description": "References to response objects"
        },
        "emptyResponse": {
          "type": "boolean",
          "default": false
        },
        "errors": {
          "$ref": "#/definitions/methodErrors"
        }
      },
      "required": [
        "name",
        "access_token_type",
        "responses"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "errors": {
      "type": "object",
      "patternProperties": {
        "^[a-z][a-z0-9_]+$": {
          "$ref": "#/definitions/error"
        }
      },
      "additionalProperties": false,
      "uniqueProperties": true
    },
    "methods": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/method"
      }
    },
    "definitions": {
      "patternProperties": {
        "^([a-zA-Z0-9_]+)?[rR]esponse$": {
          "$ref": "#/definitions/response"
        }
      },
      "uniqueProperties": true
    },
    "$schema": {
      "type": "string",
      "format": "uri-reference"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "termsOfService": {
      "type": "string",
      "format": "url"
    },
    "version": {
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== VKCOM/vk-api-schema/asr/methods.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - methods",
  "description": "Contains JSON Schema documents explaining the VK.COM API - methods",
  "termsOfService": "https://dev.vk.com/rules",
  "methods": [
    {
      "name": "asr.checkStatus",
      "description": "Returns status of the task with provided `task_id`",
      "access_token_type": [
        "service"
      ],
      "parameters": [
        {
          "name": "task_id",
          "description": "ID of ASR task in UUID format.",
          "type": "string",
          "required": true
        }
      ],
      "responses": {
        "response": {
          "$ref": "../asr/responses.json#/definitions/asr_checkStatus_response"
        }
      },
      "errors": [
        {
          "$ref": "../errors.json#/errors/api_error_asr_not_found"
        }
      ]
    },
    {
      "name": "asr.getUploadUrl",
      "description": "Returns the server address to [vk.com/dev/upload_files_2|upload audio files].",
      "access_token_type": [
        "service"
      ],
      "responses": {
        "response": {
          "$ref": "../base/responses.json#/definitions/base_getUploadServer_response"
        }
      }
    },
    {
      "name": "asr.process",
      "description": "Starts ASR task on [vk.com/dev/upload_files_2|uploaded audio file].",
      "access_token_type": [
        "service"
      ],
      "parameters": [
        {
          "name": "audio",
          "description": "This parameter is a JSON response returned from [vk.com/dev/upload_files_2|file uploading server].",
          "type": "string",
          "required": true
        },
        {
          "name": "model",
          "description": "Which model to use for recognition. `neutral` -- general purpose (interviews, TV shows, etc.), `spontaneous` -- for NSFW audios (slang, profanity, etc.)",
          "type": "string",
          "required": true,
          "enum": [
            "neutral",
            "spontaneous"
          ]
        }
      ],
      "responses": {
        "response": {
          "$ref": "../asr/responses.json#/definitions/asr_process_response"
        }
      },
      "errors": [
        {
          "$ref": "../errors.json#/errors/api_error_asr_file_is_too_big"
        },
        {
          "$ref": "../errors.json#/errors/api_error_asr_audio_duration_flooded"
        },
        {
          "$ref": "../errors.json#/errors/api_error_asr_invalid_hash"
        }
      ]
    }
  ]
}

=== VKCOM/vk-api-schema/appWidgets/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "appWidgets_getAppImageUploadServer_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "upload_url": {
              "type": "string",
              "description": "To upload an image, generate POST-request to upload_url with a file in photo field. Then call appWidgets.saveAppImage method"
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_getAppImages_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photos",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_getGroupImageUploadServer_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "upload_url": {
              "type": "string",
              "description": "To upload an image, generate POST-request to upload_url with a file in photo field. Then call appWidgets.saveAppImage method"
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_getGroupImages_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photos",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_getImagesById_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photo"
          },
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_saveAppImage_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photo",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_saveGroupImage_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photo",
          "required": true
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/utils/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "utils_domain_resolved": {
      "type": "object",
      "properties": {
        "object_id": {
          "type": "integer",
          "description": "Object ID"
        },
        "group_id": {
          "type": "integer",
          "description": "Group ID",
          "entity": "groups",
          "format": "int64"
        },
        "type": {
          "$ref": "../utils/objects.json#/definitions/utils_domain_resolved_type"
        }
      }
    },
    "utils_domain_resolved_type": {
      "type": "string",
      "description": "Object type",
      "enum": [
        "user",
        "group",
        "application",
        "event",
        "page",
        "vk_app",
        "community_application"
      ]
    },
    "utils_last_shortened_link": {
      "type": "object",
      "properties": {
        "access_key": {
          "type": "string",
          "description": "Access key for private stats"
        },
        "key": {
          "type": "string",
          "description": "Link key (characters after vk.cc/)"
        },
        "short_url": {
          "type": "string",
          "format": "uri",
          "description": "Short link URL"
        },
        "timestamp": {
          "type": "integer",
          "description": "Creation time in Unixtime"
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Full URL"
        },
        "views": {
          "type": "integer",
          "description": "Total views number"
        }
      }
    },
    "utils_link_checked": {
      "type": "object",
      "properties": {
        "link": {
          "type": "string",
          "format": "uri",
          "description": "Link URL"
        },
        "status": {
          "$ref": "../utils/objects.json#/definitions/utils_link_checked_status"
        }
      }
    },
    "utils_link_checked_status": {
      "type": "string",
      "description": "Link status",
      "enum": [
        "not_banned",
        "banned",
        "processing"
      ]
    },
    "utils_link_stats": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "description": "Link key (characters after vk.cc/)"
        },
        "stats": {
          "type": "array",
          "items": {
            "$ref": "../utils/objects.json#/definitions/utils_stats"
          }
        }
      }
    },
    "utils_link_stats_extended": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "description": "Link key (characters after vk.cc/)"
        },
        "stats": {
          "type": "array",
          "items": {
            "$ref": "../utils/objects.json#/definitions/utils_stats_extended"
          }
        }
      }
    },
    "utils_short_link": {
      "type": "object",
      "properties": {
        "access_key": {
          "type": "string",
          "description": "Access key for private stats"
        },
        "key": {
          "type": "string",
          "description": "Link key (characters after vk.cc/)"
        },
        "short_url": {
          "type": "string",
          "format": "uri",
          "description": "Short link URL"
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Full URL"
        }
      }
    },
    "utils_stats": {
      "type": "object",
      "properties": {
        "timestamp": {
          "type": "integer",
          "description": "Start time"
        },
        "views": {
          "type": "integer",
          "description": "Total views number"
        }
      }
    },
    "utils_stats_city": {
      "type": "object",
      "properties": {
        "city_id": {
          "type": "integer",
          "description": "City ID"
        },
        "views": {
          "type": "integer",
          "description": "Views number"
        }
      }
    },
    "utils_stats_country": {
      "type": "object",
      "properties": {
        "country_id": {
          "type": "integer",
          "description": "Country ID"
        },
        "views": {
          "type": "integer",
          "description": "Views number"
        }
      }
    },
    "utils_stats_extended": {
      "type": "object",
      "properties": {
        "cities": {
          "type": "array",
          "items": {
            "$ref": "../utils/objects.json#/definitions/utils_stats_city"
          }
        },
        "countries": {
          "type": "array",
          "items": {
            "$ref": "../utils/objects.json#/definitions/utils_stats_country"
          }
        },
        "sex_age": {
          "type": "array",
          "items": {
            "$ref": "../utils/objects.json#/definitions/utils_stats_sex_age"
          }
        },
        "timestamp": {
          "type": "integer",
          "description": "Start time"
        },
        "views": {
          "type": "integer",
          "description": "Total views number"
        }
      }
    },
    "utils_stats_sex_age": {
      "type": "object",
      "properties": {
        "age_range": {
          "type": "string",
          "description": "Age denotation"
        },
        "female": {
          "type": "integer",
          "description": " Views by female users"
        },
        "male": {
          "type": "integer",
          "description": " Views by male users"
        }
      }
    }
  }
}

=== VKCOM/vk-api-schema/comment/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "comment_thread": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "description": "Comments number",
          "minimum": 0,
          "required": true
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "../wall/objects.json#/definitions/wall_wall_comment"
          }
        },
        "can_post": {
          "type": "boolean",
          "description": "Information whether current user can comment the post"
        },
        "show_reply_button": {
          "type": "boolean",
          "description": "Information whether recommended to display reply button"
        },
        "groups_can_post": {
          "type": "boolean",
          "description": "Information whether groups can comment the post"
        },
        "author_replied": {
          "type": "boolean",
          "description": "Information whether author commented the thread"
        }
      }
    }
  }
}

=== VKCOM/vk-api-schema/prettyCards/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "prettyCards_create_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "owner_id": {
              "type": "integer",
              "description": "Owner ID of created pretty card",
              "entity": "owner",
              "format": "int64",
              "required": true
            },
            "card_id": {
              "type": "string",
              "description": "Card ID of created pretty card",
              "required": true
            }
          },
          "required": true
        }
      }
    },
    "prettyCards_delete_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "owner_id": {
              "type": "integer",
              "description": "Owner ID of deleted pretty card",
              "entity": "owner",
              "format": "int64",
              "required": true
            },
            "card_id": {
              "type": "string",
              "description": "Card ID of deleted pretty card",
              "required": true
            },
            "error": {
              "type": "string",
              "description": "Error reason if error happened"
            }
          },
          "required": true
        }
      }
    },
    "prettyCards_edit_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "owner_id": {
              "type": "integer",
              "description": "Owner ID of edited pretty card",
              "entity": "owner",
              "format": "int64",
              "required": true
            },
            "card_id": {
              "type": "string",
              "description": "Card ID of edited pretty card",
              "required": true
            }
          },
          "required": true
        }
      }
    },
    "prettyCards_getById_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../prettyCards/objects.json#/definitions/prettyCards_prettyCardOrError"
          },
          "required": true
        }
      }
    },
    "prettyCards_getUploadURL_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "string",
          "description": "Upload URL",
          "required": true
        }
      }
    },
    "prettyCards_get_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer",
              "description": "Total number",
              "required": true
            },
            "items": {
              "type": "array",
              "items": {
                "$ref": "../prettyCards/objects.json#/definitions/prettyCards_prettyCard"
              },
              "required": true
            }
          },
          "required": true
        }
      }
    }
  }
}

=== VKCOM/vk-api-schema/appWidgets/objects.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - objects",
  "description": "Contains JSON Schema documents explaining the VK.COM API - objects",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "appWidgets_photo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Image ID",
          "required": true
        },
        "images": {
          "type": "array",
          "items": {
            "$ref": "../base/objects.json#/definitions/base_image"
          },
          "required": true
        }
      },
      "additionalProperties": false
    },
    "appWidgets_photos": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "minimum": 0
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "../appWidgets/objects.json#/definitions/appWidgets_photo"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== VKCOM/vk-api-schema/orders/responses.json
{
  "$schema": "../schema.json",
  "version": "5.199",
  "title": "VK API JSON Schema - responses",
  "description": "Contains JSON Schema documents explaining the VK.COM API - responses",
  "termsOfService": "https://dev.vk.com/rules",
  "definitions": {
    "orders_changeState_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "string",
          "description": "New state",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "orders_getAmount_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../orders/objects.json#/definitions/orders_amount"
          },
          "required": true
        }
      },
      "additionalProperties": false
    },
    "orders_getById_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../orders/objects.json#/definitions/orders_order"
          },
          "required": true
        }
      },
      "additionalProperties": false
    },
    "orders_getUserSubscriptionById_response": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "../orders/objects.json#/definitions/orders_subscription",
          "required": true
        }
      },
      "additionalProperties": false
    },
    "orders_getUserSubscriptions_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer",
              "description": "Total number",
              "required": true
            },
            "items": {
              "type": "array",
              "items": {
                "$ref": "../orders/objects.json#/definitions/orders_subscription"
              },
              "required": true
            }
          },
          "additionalProperties": false,
          "required": true
        }
      },
      "additionalProperties": false
    },
    "orders_get_response": {
      "type": "object",
      "properties": {
        "response": {
          "type": "array",
          "items": {
            "$ref": "../orders/objects.json#/definitions/orders_order"
          },
          "required": true
        }
      },
      "additionalProperties": false
    }
  }
}
